name: Secrets

on:
   push:
      branches: [main]
   pull_request:
      types: [opened, reopened, synchronize]
   workflow_dispatch:

jobs:
   fetch-secrets:
      name: Fetch secrets
      runs-on: ubuntu-latest
      steps:
         - name: Load secrets into environment variable
           run: echo "This is my secret $DB_PASS"
           env:
              DB_PASS: ${{secrets.DB_PASSWORD}}

         - name: Read secret directly
           run: echo "This is my secret ${{secrets.DB_PASSWORD}}"
